// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-subscription.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_subscription_default = defineTool({
  name: "get_my_subscription",
  title: "Get my subscription",
  description: "Fetch the signed-in client's active subscription (type, start/end date, days remaining, paid/remaining amount, captain).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: account, error: accErr } = await supabase.from("client_accounts").select("subscriber_id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (accErr || !account) {
      return {
        content: [{ type: "text", text: "No client account linked to this user." }],
        isError: true
      };
    }
    const { data: sub, error } = await supabase.from("subscribers").select("*").eq("id", account.subscriber_id).maybeSingle();
    if (error || !sub) {
      return { content: [{ type: "text", text: error?.message ?? "Not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(sub) }],
      structuredContent: { subscription: sub }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_notifications_default = defineTool2({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List notifications for the signed-in client (most recent first).",
  inputSchema: {
    limit: z.number().int().positive().describe("Max notifications to return.").optional(),
    unreadOnly: z.boolean().describe("Only return unread notifications.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unreadOnly }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: account } = await supabase.from("client_accounts").select("subscriber_id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!account) {
      return { content: [{ type: "text", text: "No client account linked." }], isError: true };
    }
    let q = supabase.from("client_notifications").select("*").eq("subscriber_id", account.subscriber_id).order("created_at", { ascending: false }).limit(Math.min(limit ?? 20, 100));
    if (unreadOnly) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-captain-clients.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(globalThis.process.env.SUPABASE_URL, globalThis.process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_captain_clients_default = defineTool3({
  name: "list_my_captain_clients",
  title: "List captain clients",
  description: "If the signed-in user is a captain, list the subscribers assigned to them.",
  inputSchema: {
    search: z2.string().describe("Optional name substring to filter by.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data: cap } = await supabase.from("captain_accounts").select("captain_name").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!cap) {
      return {
        content: [{ type: "text", text: "This user is not linked to a captain account." }],
        isError: true
      };
    }
    let q = supabase.from("subscribers").select("*").eq("captain", cap.captain_name);
    if (search && search.trim()) q = q.ilike("name", `%${search.trim()}%`);
    const { data, error } = await q.limit(200);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xlowcsumezdzgjvjcvln";
var mcp_default = defineMcp({
  name: "gym-mcp",
  title: "2B Gym MCP",
  version: "0.1.0",
  instructions: "Tools for the 2B Gym app. Clients can read their own subscription and notifications; captains can list their assigned clients.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_subscription_default, list_my_notifications_default, list_my_captain_clients_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
